<?php
$array = array(
	"Vandal" => "http://rss.vandal.net/xml.cgi",
	"IGN" => "http://es.ign.com/articles/rss",
	"Meristation" => "http://www.meristation.com/es/rss/news/",
	"3dJuegos" => "http://www.3djuegos.com/universo/rss/rss.php?plats=1-2-3-4-5-6-7-34&tipos=noticia-analisis-avance-video-imagenes-demo&fotos=si&limit=20",
	"Ecetia" => "http://feeds.hipertextual.com/ecetia",
	"VidaExtra" => "http://feeds.weblogssl.com/vidaextra",
	"Egamers" => "http://www.egamers.com/rss.xml",
	"MundoGamers" => "http://www.mundogamers.com/rss-noticias.html",
	"VicioJuegos" => "http://www.viciojuegos.com/noticiasRSS.jsp?division=Todo",
	"TeamPlayers" => "http://www.teamplayers.es/feed/",
	"ElReino" => "http://elreino.net/rss_noticias.php",
	"VideoShock" => "http://feeds.feedburner.com/videoshock/"
);
?>
