<?php
$array = [
	"Vandal" => "http://rss.vandal.net/xml.cgi",
	"IGN" => "http://es.ign.com/articles/rss",
	"Meristation" => "http://www.meristation.com/es/rss/news/58%2B61%2B63%2B1365%2B62%2B1366%2B793%2B1102%2B40073%2B431%2B1160%2B59%2B437%2B434%2B439%2B60%2B432",
	"3dJuegos" => "http://www.3djuegos.com/universo/rss/rss.php?plats=1-2-3-4-5-6-7-34&tipos=noticia-analisis-avance-video-imagenes-demo&fotos=si&limit=20",
	"Ecetia" => "http://feeds.hipertextual.com/ecetia",
	"VidaExtra" => "http://feeds.weblogssl.com/vidaextra",
	"Egamers" => "http://www.egamers.com/others/rss.php",
	"MundoGamers" => "http://www.mundogamers.com/rss-noticias.html",
	"VicioJuegos" => "http://www.viciojuegos.com/noticiasRSS.jsp?division=Todo",
	"TeamPlayers" => "http://www.teamplayers.es/feed/",
	"ElReino" => "http://elreino.net/rss_noticias.php",
	"VideoShock" => "http://www.videoshock.es/feed/",
];

?>
